### PR TITLE
Aave-v3-arbitrum resolver

### PR DESCRIPTION
**Pull request by iri031**
**Aave-v3 arbitrum chain resolver.**
Docs: [https://docs.aave.com/developers/getting-started/v3-overview](https://docs.aave.com/developers/getting-started/v3-overview)
The Resolver has the following functions:

- `getPosition`: Returns the position of user for the tokens passed.
- `getPositionAll`: Returns the position of user for all the tokens of the market.
- `getConfiguration`: Returns if the assets are used as collateral or being borrowed.
- `getReservesList`: Returns list of tokens of the market.
- `getEmodeCategoryData`: Returns details of e-mode category passed.
- `isUsingAsCollateralOrBorrowing`: Returns collateral or borrow details for reserve index passed.
- `isUsingAsCollateral`: Returns supply details of reserve index passed.
- `isBorrow`: Returns if asset is borrowed or not.
- `getConfig`: Returns user configuration.
- `getEthPrice`: Returns eth price.
- [x] Returns user info, token info (all prices in base currency)
- [x]  Returns atoken address, stableDebtToken address, variableDebtToken address.

Updated resolver: [AaveV3 arbitrum resolver update #74](https://github.com/Instadapp/dsa-resolvers/pull/74)

### CODE REVIEW

**Comment by iri031** [comment]
Screenshot from 2022-03-09 03-21-52
Screenshot from 2022-03-09 03-22-03
Screenshot from 2022-03-09 03-22-15
Screenshot from 2022-03-09 03-22-23
Screenshot from 2022-03-09 03-22-34

**Comment by iri031** [comment]
Screenshot from 2022-03-09 12-55-49
Screenshot from 2022-03-09 12-55-59
Screenshot from 2022-03-09 12-56-12
Screenshot from 2022-03-09 12-56-23
Screenshot from 2022-03-09 12-56-32

**Comment by iri031** [comment]
Deployed Contract: 0x686497f9E8bf13F6E89382c5249C87A6df49976d

**Review by pradyuman-verma — APPROVED** [review]

**Review by thrilok209 — APPROVED** [review]

**Comment by iri031** [comment]
Deployed Contract(with latest addresses) : [0x7cdBD859f2EDA545289378112FD991571d6eb73e](https://arbiscan.io/address/0x7cdBD859f2EDA545289378112FD991571d6eb73e)

**Pull request merged**
