### PR TITLE
AaveV3-optimism resolver

### PR DESCRIPTION
**Pull request by iri031**
**Aave-v3 optimism chain resolver.**
Docs: [https://docs.aave.com/developers/getting-started/v3-overview](https://docs.aave.com/developers/getting-started/v3-overview)
The Resolver has the following functions:

- `getPosition`: Returns the position of user for the tokens passed.
- `getPositionAll`: Returns the position of user for all the tokens of the market.
- `getConfiguration`: Returns if the assets are used as collateral or being borrowed.
- `getReservesList`: Returns list of tokens of the market.
- `getEmodeCategoryData`: Returns details of e-mode category passed.
- `isUsingAsCollateralOrBorrowing`: Returns collateral or borrow details for reserve index passed.
- `isUsingAsCollateral`: Returns supply details of reserve index passed.
- `isBorrow`: Returns if asset is borrowed or not.
- `getConfig`: Returns user configuration.
- `getEthPrice`: Returns eth price.
- [x] Returns user info, token info (all prices in base currency)

Updated resolver: [AaveV3 optimism resolver update #72](https://github.com/Instadapp/dsa-resolvers/pull/72)

### CODE REVIEW

**Comment by iri031** [comment]
Screenshot from 2022-03-09 00-47-52
Screenshot from 2022-03-09 00-48-05
Screenshot from 2022-03-09 00-48-22
Screenshot from 2022-03-09 00-48-33
Screenshot from 2022-03-09 00-49-03

**Comment by iri031** [comment]
Screenshot from 2022-03-09 01-47-37

**Comment by iri031** [comment]
Deployed Contract: 0x686497f9E8bf13F6E89382c5249C87A6df49976d

**Review by pradyuman-verma — APPROVED** [review]

**Review by thrilok209 — APPROVED** [review]

**Comment by iri031** [comment]
Deployed Contract(with latest addresses): [0x7cdBD859f2EDA545289378112FD991571d6eb73e](https://optimistic.etherscan.io/address/0x7cdBD859f2EDA545289378112FD991571d6eb73e)

**Pull request merged**
