### PR TITLE
feat: added sushiswap resolver on other chains

### PR DESCRIPTION
**Pull request by pradyuman-verma**
This PR adds the sushiswap resolver on other chains as well following the mainnet implementation.
- [x] add sushiswap on the polygon.
- [x] add sushiswap on the arbitrum.
- [x] Add tests for the same.
- [x] deploy and comment addresses.

Merge #16 First.

### CODE REVIEW

**Review by KaymasJain — APPROVED** [review]

**Comment by pradyuman-verma** [comment]
**Arbitrum test**
image

**Comment by pradyuman-verma** [comment]
**mainnet test**
image

**Comment by pradyuman-verma** [comment]
**polygon test**
image

**Comment by pradyuman-verma** [comment]
Suhiswap deployed on polygon - [0xbD07728E20c49F0Fa22c82915955fbeA5E203a6a](https://polygonscan.com/address/0xbD07728E20c49F0Fa22c82915955fbeA5E203a6a)

**Comment by pradyuman-verma** [comment]
final Sushiswap deployed on polygon - [0x6d18725E0812B6fee55FF4215b154b11289D4B77](https://polygonscan.com/address/0x6d18725E0812B6fee55FF4215b154b11289D4B77)

**Comment by pradyuman-verma** [comment]
sushiswap deployed on arbitrum - [0x3BCA6531eDb2b41319fC56bA3c142367F83B65EE](https://arbiscan.io/address/0x3BCA6531eDb2b41319fC56bA3c142367F83B65EE)

**Review by KaymasJain — APPROVED** [review]

**Review by KaymasJain — APPROVED** [review]

**Pull request merged**
