### PR TITLE
feat: add yearn vault resolver

### PR DESCRIPTION
**Pull request by TBouder**
**Protocol**: https://yearn.finance
**Docs**: https://docs.yearn.finance/

Adding a resolver to the Yearn Vaults. The [connector PR can be found here](https://github.com/Instadapp/dsa-connectors/pull/69).
Here are the functions available:

- `function getPositions(address owner, address[] memory wantAddresses) public view returns (VaultData[] memory)`
Retrieve the positions for an owner, for an array of wantToken, in both deprecated and latest vaults. An array of `VaultData` is returned.

- `function getPositionsForLatest(address owner, address[] memory wantAddresses)`
Retrieve the positions for an owner, for an array of wantToken, in latest vaults. An array of `VaultData` is returned.

- `function isEmergencyShutdown(YearnV2Interface vault) public view returns (bool)`
Indicate if a Vault is in Emergency Shutdown state (no deposit and more stuff)

- `function getPricePerShare(YearnV2Interface vault) public view returns (uint256)`
Retrieve the price for 1 share of this vault in `Want` token

- `function getAvailableDepositLimit(YearnV2Interface vault) public view returns (uint256)`
Retrieve the deposit limit for this vault. That's the max amount of want we can deposit in the vault right now.

- `function getBalance(address owner, YearnV2Interface vault) public view returns (uint256)`
Retrieve the number of shares (aka erc20 balance) for the owner, for this vault.

- `function getExpectedShareValue(address owner, YearnV2Interface vault) public view returns (uint256)`
Compute balanceOf x pricePerShare. It can help to get an overview of the value of our shares.

- `function isWantSupported(address want) public view returns (bool)`
Check if a specific `want` token can be send to a Vault. (Does a Vault exist for this want).

- `function latestForWant(address want) public view returns (address)`
Retrieve the latest vault for a `want` token

- `function numVaultsForWant(address want) public view returns (uint256 numVaults)`
Retrieve the number of Vaults for a `want` token

- `function listVaultsForWant(address want) public view returns (address[] memory vaultAddresses)`
List the vaults for a `want` token. Resolve an array of addresses

The `vaultData` struct is returned with the `getPositions` functions:
```
    struct VaultData {
        address vaultLatestVersion; //for a given want, latest vault to user
        address vault; //vault used to get theses vaultData
        address want; //want used to get theses vaultData
        uint256 pricePerShare; //price for 1 share of this vault
        uint256 availableDepositLimit; //current deposit limit for this vault
        uint256 totalAssets; //the total quantity of all assets under control of this vault
        uint256 balanceOf; //amount of shares (vault Tokens) for this vault
        uint256 wantBalanceOf; //amount of want currently in the user's wallet
        bool isDeprecated; //is this vault the latest version for this want ?
        bool emergencyShutdown; //is this vault in an emergencyShutdown situation ?
    }
```

Some test has been added to test the different functions.

### CODE REVIEW

**Comment by thrilok209** [comment]
@TBouder expectedShareValue in the VaultData struct is `wantBalanceOf`?

**Comment by TBouder** [comment]
A new commit has been pushed with the following elements:
- Updating the VaultData
```diff
    struct VaultData {
        address vaultLatestVersion;
        address vault;
        address want;
        uint256 pricePerShare;
        uint256 availableDepositLimit;
        uint256 totalAssets;
        uint256 balanceOf;
        uint256 wantBalanceOf;
+      uint256 expectedShareValue;
+      uint256 decimals;
        bool isDeprecated;
        bool emergencyShutdown;
    }
```
- A new 'standalone' function `getTotalAssets` has been added (get the total amount of want managed by this vault)
- Splitting the code for the `getPositions` functions with an `_prepareVaultData` function
- The `getExpectedShareValue` has been updated to fix the computation (adding `/ 10 ** decimals`)
- The tests has been updated to check actual data based on the blocknumber
- A test function for `getTotalAssets` has been added
- A test function for `getExpectedShareValue` has been added

**Review by thrilok209 — APPROVED** [review]

**Comment by thrilok209** [comment]
@TBouder How is the net APY calculated?

**Comment by saltyfacu** [comment]
Hi @thrilok209! In the website, we use last week's difference in pricePerShare and extrapolate that. Put APY depends on third-party protocols so predicting is not accurate at all. We report past APY. 

You can also use our API. That's what we use for our website.

API URL: https://api.yearn.finance/v1/chains/1/vaults/all

Is it ok for you to do it that way?

**Comment by TBouder** [comment]
We are using this code for ape.tax to get some APY:
You can check the code in it's context here : https://github.com/fameal/ape-tax/blob/master/pages/%5Bslug%5D/index.js#L168

```js
const	block = await provider.getBlockNumber();
const	activationTimestamp = Number(activation); //Activation can be retrieve from the contract. Timestamp when the contract was init
const	blockActivated = Number(await fetchBlockTimestamp(activationTimestamp) || 0); //etherscan API to get the block timestamp
const	averageBlockPerWeek = 269 * 24 * 7;
const	averageBlockPerMonth = 269 * 24 * 30;
const	blockLastWeekRef = (block - averageBlockPerWeek) < blockActivated ? blockActivated : (block - averageBlockPerWeek);
const	blockLastMonthRef = (block - averageBlockPerMonth) < blockActivated ? blockActivated : (block - averageBlockPerMonth);

const	vaultContract = new ethers.Contract(
	vault.VAULT_ADDR, ['function pricePerShare() public view returns (uint256)'], provider
);
const [_pastPricePerShareWeek, _pastPricePerShareMonth] = await Promise.all([
	vaultContract.pricePerShare({blockTag: blockLastWeekRef}),
	vaultContract.pricePerShare({blockTag: blockLastMonthRef}),
]);
const	currentPrice = ethers.utils.formatUnits(pricePerShare, decimals.toNumber());
const	pastPriceWeek = ethers.utils.formatUnits(_pastPricePerShareWeek, decimals.toNumber());
const	pastPriceMonth = ethers.utils.formatUnits(_pastPricePerShareMonth, decimals.toNumber());
const	weekRoi = (currentPrice / pastPriceWeek - 1);
const	monthRoi = (currentPrice / pastPriceMonth - 1);
const	inceptionROI = (currentPrice - 1);

_grossAPRWeek = (weekRoi ? `${(weekRoi * 100).toFixed(2)}%` : '-');
_grossAPRMonth = (monthRoi ? `${(monthRoi * 100).toFixed(2)}%` : '-');
_grossAPRInception = (inceptionROI ? `${(inceptionROI * 100).toFixed(4)}%` : '-');
```

**Comment by TBouder** [comment]
Contract deployed and verified here : [0x3f6DCA8a0b7d04737BC3B2aEAbeB1C09431581f0](https://etherscan.io/address/0x3f6DCA8a0b7d04737BC3B2aEAbeB1C09431581f0#code)

**Pull request merged**
