### PR TITLE
AaveV3-optimism resolver update

### PR DESCRIPTION
**Pull request by iri031**
Updated resolver: 
- [x] Returns token info, atoken address, stableDebtToken address, variableDebtToken address, atoken symbol, atoken decimals.
- [x] Returns rewards info related to assets as well.

### CODE REVIEW

**Comment by iri031** [comment]
Screenshot from 2022-03-09 13-40-16
Screenshot from 2022-03-09 13-40-26
Screenshot from 2022-03-09 13-40-36
Screenshot from 2022-03-09 13-40-48
Screenshot from 2022-03-09 13-40-58

**Comment by iri031** [comment]
Screenshot from 2022-03-09 21-44-50
Screenshot from 2022-03-09 21-45-03
Screenshot from 2022-03-09 21-45-21
Screenshot from 2022-03-09 21-45-35
Screenshot from 2022-03-09 21-45-55
Screenshot from 2022-03-09 21-46-08
Screenshot from 2022-03-09 21-46-31
Screenshot from 2022-03-09 21-46-42

**Comment by iri031** [comment]
Deployed Contract: [0xa720C0B9A659817ecc0807b74D8e7Cf597268740](https://optimistic.etherscan.io/address/0xa720C0B9A659817ecc0807b74D8e7Cf597268740)

**Comment by iri031** [comment]
Deployed Contract(with latest addresses): [0x7cdBD859f2EDA545289378112FD991571d6eb73e](https://optimistic.etherscan.io/address/0x7cdBD859f2EDA545289378112FD991571d6eb73e)

**Review by pradyuman-verma — APPROVED** [review]

**Pull request merged**
