### PR TITLE
Aave-v3-avalanche resolver

### PR DESCRIPTION
**Pull request by iri031**
**Aave-v3 avalanche chain resolver.**
Docs: [https://docs.aave.com/developers/getting-started/v3-overview](https://docs.aave.com/developers/getting-started/v3-overview)
The Resolver has the following functions:

- `getPosition`: Returns the position of user for the tokens passed.
- `getPositionAll`: Returns the position of user for all the tokens of the market.
- `getConfiguration`: Returns if the assets are used as collateral or being borrowed.
- `getReservesList`: Returns list of tokens of the market.
- `getEmodeCategoryData`: Returns details of e-mode category passed.
- `isUsingAsCollateralOrBorrowing`: Returns collateral or borrow details for reserve index passed.
- `isUsingAsCollateral`: Returns supply details of reserve index passed.
- `isBorrow`: Returns if asset is borrowed or not.
- `getConfig`: Returns user configuration.
- `getEthPrice`: Returns eth price.
- [x] Returns user info, token info (all prices in base currency)

Updated resolver: [AaveV3 avalanche resolver update #73](https://github.com/Instadapp/dsa-resolvers/pull/73)

### CODE REVIEW

**Comment by iri031** [comment]
Screenshot from 2022-03-08 23-29-42
Screenshot from 2022-03-08 23-29-56
Screenshot from 2022-03-08 23-30-10
Screenshot from 2022-03-08 23-30-26
Screenshot from 2022-03-08 23-30-41

**Comment by iri031** [comment]
Screenshot from 2022-03-09 02-23-35

**Comment by iri031** [comment]
Deployed contract: [0x686497f9E8bf13F6E89382c5249C87A6df49976d](https://snowtrace.io/address/0x686497f9E8bf13F6E89382c5249C87A6df49976d)

**Review by pradyuman-verma — APPROVED** [review]

**Review by thrilok209 — APPROVED** [review]

**Comment by iri031** [comment]
Deployed Contract(with latest addresses): [0x7cdBD859f2EDA545289378112FD991571d6eb73e](https://snowtrace.io/address/0x7cdBD859f2EDA545289378112FD991571d6eb73e)

**Pull request merged**
