### PR TITLE
Aave v3 avalanche resolver update

### PR DESCRIPTION
**Pull request by iri031**
Updated resolver: 
- [x] Returns token info, atoken address, stableDebtToken address, variableDebtToken address, atoken symbol, atoken decimals.
- [x] Returns rewards info related to assets as well.

### CODE REVIEW

**Comment by iri031** [comment]
Screenshot from 2022-03-09 14-31-23
Screenshot from 2022-03-09 14-31-34
Screenshot from 2022-03-09 14-31-45
Screenshot from 2022-03-09 14-31-55
Screenshot from 2022-03-09 14-32-11

**Comment by iri031** [comment]
Screenshot from 2022-03-09 22-48-38
Screenshot from 2022-03-09 22-48-53
Screenshot from 2022-03-09 22-49-07
Screenshot from 2022-03-09 22-49-20
Screenshot from 2022-03-09 22-49-34
Screenshot from 2022-03-09 22-49-49
Screenshot from 2022-03-09 22-50-01
Screenshot from 2022-03-09 22-50-14

**Comment by iri031** [comment]
Delpoyed Contract: [0xa720C0B9A659817ecc0807b74D8e7Cf597268740](https://snowtrace.io/address/0xa720C0B9A659817ecc0807b74D8e7Cf597268740)

**Comment by iri031** [comment]
Deployed Contract(with latest addresses): [0x7cdBD859f2EDA545289378112FD991571d6eb73e](https://snowtrace.io/address/0x7cdBD859f2EDA545289378112FD991571d6eb73e)

**Review by pradyuman-verma — APPROVED** [review]

**Pull request merged**
